sudo: false  # Use container-based infrastructure
language: node_js
node_js:
  - "6.14"

script: >
    npm run build &&
    npm run test &&
    npm run flow-check &&
    npm run lint &&
    npm run coverage &&
    ./scripts/post-coverage.sh
